### ISSUE TITLE
Black output video or segfault

### ISSUE THREAD

**Issue by jorritsmit** [tbl3rd/Pyramids#1]
Hi,

I compiled the code on ubuntu 64-bit using OpenCV 3.2 and used the reference videos from the MIT paper. (crane_crop.avi, baby.avi, etc) and live camera. live camera and baby.avi give me a black screen. I tried different input parameters and copied the ones used in the paper as well. crane_crop.avi even gives me a segfault.

Are these known issues for you and can you point me in the right direction to look? I will work on it anyway and I understand if this code is provided as is, but I thought maybe you encountered the same problems.

Thanks

**Comment by tbl3rd** [comment]
Thank you for trying Pyramids.
I haven't compiled it since it
was posted, and have not tried
it with OpenCV 3.2 yet.

I should have some time to look
at it tomorrow.  What version of
Qt do you use?  Did you get any
diagnostics from qmake?

**Comment by jorritsmit** [comment]
Thanks for the quick response. I am using qt 5.6.1 with qt creator 4. I normally use sublimetext with CMake, so i might misunderstand you, but i attached a file containing the debug information (-d flag) when running qmake. Everything compiled out of the box apart from the fact i had to include Qtwidgets instead of Qtgui and <opencv2/videoio.hpp> instead of  <opencv2/highgui/highgui.hpp>.

[qmake_debug.txt](https://jorritsmit.stackstorage.com/s/e8qWSrMix9W2JUg)

**Comment by jorritsmit** [comment]
btw this is an example of what happens: [baby_ampl.avi](https://jorritsmit.stackstorage.com/s/5M8lP9AlLBNBuua)

**Comment by tbl3rd** [comment]
That looks like filter instability.
Last time I debugged that, it was
because a bug in the Qt plumbing
was doubling "new frame" signals.

**Comment by jorritsmit** [comment]
bypassing the Butterworth filter gave me this result: [baby_ampl.avi](https://jorritsmit.stackstorage.com/s/sRC32v1IvgZNzUs). So I guess some lower level pyramids have Inf or NaN values? Thanks for pointing me in the right direction, I'll update when i found the problem

**Comment by jorritsmit** [comment]
going back to OpenCV 2.4.9 fixed it. I'll close this issue, since it obviously has something to do with OpenCV.

**Comment by tbl3rd** [comment]
Good to know. Thanks.
I have not got it to build
with Qt 5.8 yet.
